services:
  - type: web
    name: scrapai-api
    env: python
    plan: free
    buildCommand: |
      python -m pip install --upgrade pip
      pip install --use-deprecated=legacy-resolver -r requirements.txt
    startCommand: python backend/main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false

  - type: worker
    name: scrapai-telegram
    env: python
    plan: free
    buildCommand: |
      python -m pip install --upgrade pip
      pip install --use-deprecated=legacy-resolver -r requirements.txt
    startCommand: python telegram_bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
